/* GENERATED by hash_check.py from fw/playlist.inc. Do not edit. */
#include "hostio.h"

static char pl_upper(char c) { return (c >= 'a' && c <= 'z') ? (char)(c - 32) : c; }

static uint32_t pl_name_hash(const char *name)
{
    uint32_t h = 2166136261u;
    for (uint32_t i = 0; name[i]; i++) {
        h ^= (uint32_t)(uint8_t)pl_upper(name[i]);
        h *= 16777619u;
    }
    h &= 0x7FFFFFFFu;
    return h ? h : 1u;
}

int main(void)
{
    hputu(pl_name_hash("playlist.m3u")); hnl();
    hputu(pl_name_hash("Shenanigans.m3u")); hnl();
    hputu(pl_name_hash("Goose - Shenanigans Nite Club.m3u")); hnl();
    hputu(pl_name_hash("Crash Test Dummies - God Shuffled His Feet.m3u")); hnl();
    hputu(pl_name_hash("crash test dummies - god shuffled his feet.m3u")); hnl();
    hputu(pl_name_hash("scrolltest.m3u")); hnl();
    hputu(pl_name_hash("A.m3u")); hnl();
    hputu(pl_name_hash("Bob's & Co - 100% (Live!).m3u")); hnl();
    return 0;
}
