#!/usr/bin/env python3
"""Checks the core's pl_name_hash() against tools/make_playlist_index.py.

These two must agree exactly or the core reopens nothing: the firmware hashes
the name APF reports, the tool hashes the name in playlists.m3u, and a single
bit of disagreement means the remembered playlist is never found. The failure
would be silent and would look like "persistence still doesn't work".

The C is not re-implemented here. It is EXTRACTED from fw/playlist.inc and
compiled, so the thing under test is the shipping source and cannot drift from
it by being edited separately. It then runs under tools/rv32sim.py -- same
32-bit wrapping, same char signedness as the real target.

    python tools/host/hash_check.py
"""
import io
import os
import re
import subprocess
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.abspath(os.path.join(HERE, '..', '..'))
sys.path.insert(0, os.path.join(ROOT, 'tools'))

from make_playlist_index import fnv1a_31            # noqa: E402

NAMES = [
    'playlist.m3u',
    'Shenanigans.m3u',
    'Goose - Shenanigans Nite Club.m3u',
    'Crash Test Dummies - God Shuffled His Feet.m3u',
    'crash test dummies - god shuffled his feet.m3u',   # case must not matter
    'scrolltest.m3u',
    'A.m3u',
    "Bob's & Co - 100% (Live!).m3u",                    # punctuation
]


def extract(src, sig):
    """Pull one function out of the firmware source, brace-balanced."""
    i = src.index(sig)
    j = src.index('{', i)
    depth = 0
    for k in range(j, len(src)):
        if src[k] == '{':
            depth += 1
        elif src[k] == '}':
            depth -= 1
            if depth == 0:
                return src[i:k + 1]
    raise SystemExit('unbalanced braces extracting %s' % sig)


def main():
    inc = io.open(os.path.join(ROOT, 'fw', 'playlist.inc'),
                  encoding='utf-8').read()
    upper = extract(inc, 'static char pl_upper')
    hashfn = extract(inc, 'static uint32_t pl_name_hash')

    gen = os.path.join(HERE, 'hash_gen.c')
    with io.open(gen, 'w', encoding='utf-8', newline='\n') as f:
        f.write('/* GENERATED by hash_check.py from fw/playlist.inc. '
                'Do not edit. */\n')
        f.write('#include "hostio.h"\n\n')
        f.write(upper + '\n\n')
        f.write(hashfn + '\n\n')
        f.write('int main(void)\n{\n')
        for n in NAMES:
            esc = n.replace('\\', '\\\\').replace('"', '\\"')
            f.write('    hputu(pl_name_hash("%s")); hnl();\n' % esc)
        f.write('    return 0;\n}\n')

    gcc = os.path.join(ROOT, 'toolchain',
                       'xpack-riscv-none-elf-gcc-15.2.0-1', 'bin',
                       'riscv-none-elf-gcc.exe')
    elf = os.path.join(HERE, 'hash.elf')
    cmd = [gcc, '-march=rv32im', '-mabi=ilp32', '-mno-relax', '-O2',
           '-ffreestanding', '-nostdlib', '-nostartfiles',
           '-T', os.path.join(HERE, 'link.ld'), '-o', elf,
           os.path.join(HERE, 'start.S'), gen, '-lgcc']
    r = subprocess.run(cmd, capture_output=True, text=True)
    if r.returncode:
        print(r.stderr)
        return 2

    out = subprocess.run(
        [sys.executable, os.path.join(ROOT, 'tools', 'rv32sim.py'), elf],
        capture_output=True, text=True)
    got = [int(x) for x in out.stdout.split()]
    if len(got) != len(NAMES):
        print('expected %d hashes, got %d\n%s%s'
              % (len(NAMES), len(got), out.stdout, out.stderr))
        return 2

    bad = 0
    print('%-48s %-10s %-10s' % ('name', 'firmware', 'tool'))
    for n, g in zip(NAMES, got):
        want = fnv1a_31(n)
        ok = (g == want)
        bad += 0 if ok else 1
        print('%-48s %-10d %-10d %s' % (n[:48], g, want, '' if ok else 'MISMATCH'))

    # Case folding is the one behaviour actively relied on: APF's spelling and
    # the text file's need not match, and only the card is authoritative.
    a = fnv1a_31('Crash Test Dummies - God Shuffled His Feet.m3u')
    b = fnv1a_31('crash test dummies - god shuffled his feet.m3u')
    print('\ncase folding: %s' % ('same hash, as required'
                                  if a == b else 'DIFFERS -- broken'))
    bad += 0 if a == b else 1

    print('\n%s' % ('firmware and tool agree on every name'
                    if not bad else '%d MISMATCH(ES)' % bad))
    return 1 if bad else 0


if __name__ == '__main__':
    sys.exit(main())
