#!/usr/bin/env python3
"""Checks the core's lrc_parse() against a file of known structure.

Two reasoning-based fixes to the lyrics meter missed in a row, which is where
this project's own rule says to stop fixing and start measuring. So the parser
is exercised directly rather than argued about.

The C is not re-implemented here. It is EXTRACTED from fw/lyrics.inc and
compiled, so the thing under test is the shipping source and cannot drift from
it by being edited separately. It then runs under tools/rv32sim.py -- same
32-bit wrapping, same char signedness as the real target.

The input is SYNTHETIC, with the same shape the real files were measured to
have: every line timestamped `[mm:ss.xx]`, no metadata lines, LF endings. The
parser cares about structure and never about the words, so synthetic input
tests it exactly as well as real input would.

Prints only structure -- line count, timestamps, text lengths. What is being
verified is that N lines in produce N lines out with ascending times, which is
precisely what a stuck meter would fail.

    python tools/host/lrc_check.py
"""
import io
import os
import subprocess
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.abspath(os.path.join(HERE, '..', '..'))

# (minutes, seconds, centiseconds, text length) -- shaped like the real files
LINES = [(0, 1, 50), (0, 5, 0), (0, 9, 25), (0, 13, 99), (0, 30, 10),
         (1, 0, 0), (1, 4, 5), (1, 59, 95), (2, 0, 0), (3, 21, 40)]


def extract(src, sig):
    """Pull one function out of the firmware source, brace-balanced."""
    i = src.index(sig)
    j = src.index('{', i)
    depth = 0
    for k in range(j, len(src)):
        if src[k] == '{':
            depth += 1
        elif src[k] == '}':
            depth -= 1
            if depth == 0:
                return src[i:k + 1]
    raise SystemExit('unbalanced braces extracting %s' % sig)


def main():
    inc = io.open(os.path.join(ROOT, 'fw', 'lyrics.inc'),
                  encoding='utf-8').read()
    parse = extract(inc, 'static void lrc_parse')
    index = extract(inc, 'static uint32_t lrc_index_for')

    # Build the input the same way a real file is laid out.
    text = ''
    for (mm, ss, cs) in LINES:
        text += '[%02d:%02d.%02d]word word word\n' % (mm, ss, cs)

    gen = os.path.join(HERE, 'lrc_gen.c')
    with io.open(gen, 'w', encoding='utf-8', newline='\n') as f:
        f.write('/* GENERATED by lrc_check.py from fw/lyrics.inc. '
                'Do not edit. */\n')
        f.write('#include "hostio.h"\n\n')
        f.write('#define LRC_TEXT_MAX 3072u\n')
        f.write('#define LRC_LINES    64u\n')
        f.write('#define LRC_NOTIME   0xFFFFu\n\n')
        f.write('static char     lrc_text[LRC_TEXT_MAX];\n')
        f.write('static uint16_t lrc_off[LRC_LINES];\n')
        f.write('static uint16_t lrc_sec[LRC_LINES];\n')
        f.write('static uint16_t lrc_n;\n')
        f.write('static uint8_t  lrc_synced;\n\n')
        f.write(parse + '\n\n')
        f.write(index + '\n\n')
        esc = text.replace('\\', '\\\\').replace('"', '\\"').replace('\n', '\\n')
        f.write('static const char SRC[] = "%s";\n\n' % esc)
        f.write('int main(void)\n{\n')
        f.write('    uint32_t n = 0;\n')
        f.write('    while (SRC[n]) { lrc_text[n] = SRC[n]; n++; }\n')
        f.write('    lrc_text[n] = 0;\n')
        f.write('    lrc_parse(n);\n')
        f.write('    hputu(lrc_n); hnl();\n')
        f.write('    hputu(lrc_synced); hnl();\n')
        f.write('    for (uint32_t i = 0; i < lrc_n; i++) {\n')
        f.write('        uint32_t L = 0; const char *p = lrc_text + lrc_off[i];\n')
        f.write('        while (p[L]) L++;\n')
        f.write('        hputu(lrc_sec[i]); hputc(32); hputu(L); hnl();\n')
        f.write('    }\n')
        # a few lookups, to prove the index advances with time
        f.write('    hputu(lrc_index_for(0)); hputc(32);\n')
        f.write('    hputu(lrc_index_for(100)); hputc(32);\n')
        f.write('    hputu(lrc_index_for(650)); hputc(32);\n')
        f.write('    hputu(lrc_index_for(5000)); hnl();\n')
        f.write('    return 0;\n}\n')

    gcc = os.path.join(ROOT, 'toolchain',
                       'xpack-riscv-none-elf-gcc-15.2.0-1', 'bin',
                       'riscv-none-elf-gcc.exe')
    elf = os.path.join(HERE, 'lrc.elf')
    cmd = [gcc, '-march=rv32im', '-mabi=ilp32', '-mno-relax', '-O2',
           '-ffreestanding', '-nostdlib', '-nostartfiles',
           '-T', os.path.join(HERE, 'link.ld'), '-o', elf,
           os.path.join(HERE, 'start.S'), gen, '-lgcc']
    r = subprocess.run(cmd, capture_output=True, text=True)
    if r.returncode:
        print(r.stderr)
        return 2

    out = subprocess.run(
        [sys.executable, os.path.join(ROOT, 'tools', 'rv32sim.py'), elf],
        capture_output=True, text=True)
    if out.returncode:
        print(out.stderr)
        return 2

    rows = [l for l in out.stdout.splitlines() if l.strip()]
    got_n = int(rows[0])
    synced = int(rows[1])
    want_n = len(LINES)

    print('lines parsed : %d   (expected %d)' % (got_n, want_n))
    print('synced flag  : %d   (expected 1)' % synced)
    print()
    print('  #   tenths textlen  expected')
    ok = (got_n == want_n and synced == 1)
    for i in range(min(got_n, want_n)):
        secs, ln = (int(x) for x in rows[2 + i].split())
        want = (LINES[i][0] * 60 + LINES[i][1]) * 10 + LINES[i][2] // 10
        mark = '' if secs == want else '   <-- WRONG'
        if secs != want or ln == 0:
            ok = False
        print('  %-3d %-5d %-8d %d%s' % (i, secs, ln, want, mark))

    if len(rows) > 2 + min(got_n, want_n):
        print()
        print('lrc_index_for(0,100,650,5000) = %s' % rows[-1])

    print()
    print('PARSER OK' if ok else 'PARSER FAULT -- see above')
    return 0 if ok else 1


sys.exit(main())
