/* GENERATED by lrc_check.py from fw/lyrics.inc. Do not edit. */
#include "hostio.h"

#define LRC_TEXT_MAX 3072u
#define LRC_LINES    64u
#define LRC_NOTIME   0xFFFFu

static char     lrc_text[LRC_TEXT_MAX];
static uint16_t lrc_off[LRC_LINES];
static uint16_t lrc_sec[LRC_LINES];
static uint16_t lrc_n;
static uint8_t  lrc_synced;

static void lrc_parse(uint32_t len)
{
    lrc_n = 0; lrc_synced = 0;
    uint32_t i = 0;

    while (i < len && lrc_n < LRC_LINES) {
        while (i < len && (lrc_text[i] == '\n' || lrc_text[i] == '\r')) i++;
        if (i >= len) break;

        uint32_t a = i;
        while (i < len && lrc_text[i] != '\n' && lrc_text[i] != '\r') i++;
        uint32_t b = i;

        /* STEP PAST THE TERMINATOR BEFORE the NUL is written over it below.
         *
         * Terminating each line in place is what lets lrc_off hold offsets
         * instead of pointers -- the buffer is storage and index at once. But
         * the NUL lands exactly where the newline was, and the scan at the top
         * of this loop skips NEWLINES. Writing first left `i` parked on a NUL
         * it did not recognise, so every line after the first was parsed
         * starting at that NUL: empty text, no timestamp. Only line 0 carried a
         * time, lrc_index_for() could only return 0, and the meter sat on the
         * first lyric for the whole song. */
        if (i < len) i++;

        while (b > a && lrc_text[b - 1u] == ' ') b--;

        uint32_t t = LRC_NOTIME, p = a;
        while (p + 1u < b && lrc_text[p] == '[') {
            uint32_t q = p + 1u, mm = 0, ss = 0, cs = 0;
            int ok = 0;
            if (lrc_text[q] >= '0' && lrc_text[q] <= '9') {
                while (q < b && lrc_text[q] >= '0' && lrc_text[q] <= '9')
                    mm = mm * 10u + (uint32_t)(lrc_text[q++] - '0');
                if (q < b && lrc_text[q] == ':') {
                    q++;
                    while (q < b && lrc_text[q] >= '0' && lrc_text[q] <= '9')
                        ss = ss * 10u + (uint32_t)(lrc_text[q++] - '0');
                    ok = 1;
                    /* The fractional part, which used to be skipped along with
                     * everything else up to the ']'. Both `.` and `:` appear as
                     * the separator in the wild. One digit means tenths
                     * already; two means centiseconds. */
                    if (q < b && (lrc_text[q] == '.' || lrc_text[q] == ':')) {
                        q++;
                        uint32_t d = 0;
                        while (q < b && d < 2u &&
                               lrc_text[q] >= '0' && lrc_text[q] <= '9') {
                            cs = cs * 10u + (uint32_t)(lrc_text[q++] - '0');
                            d++;
                        }
                        if (d == 1u) cs *= 10u;
                    }
                }
            }
            while (q < b && lrc_text[q] != ']') q++;
            if (q >= b) break;
            q++;
            if (ok && t == LRC_NOTIME) {
                /* TENTHS, not seconds. uint16 holds 6553 s that way -- an hour
                 * and three quarters, past any track -- and a second of slop
                 * was audible on fast passages where lines land close. */
                uint32_t v = (mm * 60u + ss) * 10u + cs / 10u;
                t = (v < LRC_NOTIME) ? v : (LRC_NOTIME - 1u);
                lrc_synced = 1u;
            }
            p = q;
        }
        while (p < b && lrc_text[p] == ' ') p++;

        if (p < b) {
            lrc_off[lrc_n] = (uint16_t)p;
            lrc_sec[lrc_n] = (uint16_t)t;
            lrc_text[b]    = 0;
            lrc_n++;
        }
    }
}

static uint32_t lrc_index_for(uint32_t t10)
{
    uint32_t k = 0;
    for (uint32_t i = 0; i < lrc_n; i++)
        if (lrc_sec[i] != LRC_NOTIME && (uint32_t)lrc_sec[i] <= t10) k = i;
    return k;
}

static const char SRC[] = "[00:01.50]word word word\n[00:05.00]word word word\n[00:09.25]word word word\n[00:13.99]word word word\n[00:30.10]word word word\n[01:00.00]word word word\n[01:04.05]word word word\n[01:59.95]word word word\n[02:00.00]word word word\n[03:21.40]word word word\n";

int main(void)
{
    uint32_t n = 0;
    while (SRC[n]) { lrc_text[n] = SRC[n]; n++; }
    lrc_text[n] = 0;
    lrc_parse(n);
    hputu(lrc_n); hnl();
    hputu(lrc_synced); hnl();
    for (uint32_t i = 0; i < lrc_n; i++) {
        uint32_t L = 0; const char *p = lrc_text + lrc_off[i];
        while (p[L]) L++;
        hputu(lrc_sec[i]); hputc(32); hputu(L); hnl();
    }
    hputu(lrc_index_for(0)); hputc(32);
    hputu(lrc_index_for(100)); hputc(32);
    hputu(lrc_index_for(650)); hputc(32);
    hputu(lrc_index_for(5000)); hnl();
    return 0;
}
