#!/usr/bin/env python3
"""Runs the core's text path against Python's, before it costs a hardware cycle.

Three things have to agree or Japanese titles come out wrong in ways that look
like a font bug:

  * the UTF-8 decoder and the buffer-truncation rules (fw/utf8.h),
  * the tag decoders -- UTF-16 with either BOM, and the encoding-0 guess
    between real UTF-8 and Windows-1252 (fw/player.c),
  * fb_resolve(), whose glyph index must land on the same glyph that
    tools/gen_font_ext.py wrote into mp3font.bin.

The C is EXTRACTED from the shipping source rather than re-implemented here, so
what runs is what ships, and it runs under tools/rv32sim.py -- same 32-bit
wrapping and char signedness as the target.

    python tools/host/text_check.py
"""
import io
import os
import re
import struct
import subprocess
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.abspath(os.path.join(HERE, '..', '..'))
sys.path.insert(0, os.path.join(ROOT, 'tools'))

TC = os.path.join(ROOT, 'toolchain', 'xpack-riscv-none-elf-gcc-15.2.0-1', 'bin')
GCC = os.path.join(TC, 'riscv-none-elf-gcc.exe')


def extract(src, sig):
    i = src.index(sig)
    j = src.index('{', i)
    depth = 0
    for k in range(j, len(src)):
        if src[k] == '{':
            depth += 1
        elif src[k] == '}':
            depth -= 1
            if depth == 0:
                return src[i:k + 1]
    raise SystemExit('unbalanced braces extracting %s' % sig)


def cstr(b):
    return '"' + ''.join('\\x%02x' % c for c in b) + '"'


# ---- cases ----------------------------------------------------------------
# (label, bytes, encoding byte) for id3_text_body
TAGS = [
    ('utf8 kanji',      '\u5b87\u591a\u7530\u30d2\u30ab\u30eb'.encode('utf-8'), 3),
    ('utf8 ascii',      b'Daft Punk', 3),
    ('utf16le bom',     b'\xff\xfe' + '\u521d\u604b'.encode('utf-16-le'), 1),
    ('utf16be bom',     b'\xfe\xff' + '\u521d\u604b'.encode('utf-16-be'), 1),
    ('utf16be no bom',  '\u00c9dith'.encode('utf-16-be'), 2),
    ('latin1 bytes',    'Bj\u00f6rk'.encode('latin-1'), 0),
    ('cp1252 quotes',   b'Rock \x93n\x94 Roll \x92s', 0),
    ('utf8 in enc0',    '\u30d3\u30fc\u30eb'.encode('utf-8'), 0),
    ('bad utf8 tail',   b'abc\xe6\x97', 3),
    ('surrogate pair',  b'\xff\xfe' + '\U0001f600ok'.encode('utf-16-le'), 1),
]

# Strings for the width/truncation path
TRUNC = [
    ('\u6771\u4eac\u97f3\u697d' * 6, 16),     # kanji, cut mid-character
    ('Tokyo Sound', 8),
    ('\u00e9\u00e8\u00ea' * 10, 9),
]


def main():
    player = io.open(os.path.join(ROOT, 'fw', 'player.c'), encoding='utf-8').read()
    utf8h = io.open(os.path.join(ROOT, 'fw', 'utf8.h'), encoding='utf-8').read()

    cp1252 = player[player.index('static const uint16_t cp1252_hi[32]'):]
    cp1252 = cp1252[:cp1252.index('};') + 2]

    parts = [
        utf8h.replace('#ifndef UTF8_H', '').replace('#define UTF8_H', '')
             .replace('#endif', '').replace('#include <stdint.h>', ''),
        cp1252,
        extract(player, 'static int u8_valid'),
        extract(player, 'static uint32_t txt8_to_utf8'),
        extract(player, 'static int id3_text_body'),
        extract(player, 'static uint32_t fb_resolve'),
    ]

    gen = os.path.join(HERE, 'text_gen.c')
    with io.open(gen, 'w', encoding='utf-8', newline='\n') as f:
        f.write('/* GENERATED by text_check.py from fw/. Do not edit. */\n')
        f.write('#include "hostio.h"\n')
        f.write('#include "../../fw/font_metrics.h"\n')
        f.write('#include "../../fw/font_ext.h"\n\n')
        f.write('#define ID3_OK 0\n#define ID3_NO_FRAME 1\n')
        f.write('#define FB_EXT 0x80000000u\n')
        f.write('static uint8_t fext_ok = 1;\n\n')
        f.write('\n\n'.join(parts) + '\n\n')
        f.write('''
static void emit(const char *tag, const char *s)
{
    hputs(tag); hputc(' ');
    while (*s) { hputu((unsigned char)*s); hputc(','); s++; }
    hputc('\\n');
}

int main(void)
{
    char out[96];
''')
        for label, body, enc in TAGS:
            f.write('    { static const unsigned char b[] = %s;\n'
                    '      id3_text_body(b, sizeof(b), out, sizeof(out));\n'
                    '      emit("%s", out); }\n'
                    % (cstr(bytes([enc]) + body), label.replace(' ', '_')))
        for s, cap in TRUNC:
            f.write('    { static const char *src = %s;\n'
                    '      char t[%d]; uint32_t i = 0;\n'
                    '      while (src[i] && i < sizeof(t) - 1u) { t[i] = src[i]; i++; }\n'
                    '      t[u8_trim(t, i)] = 0;\n'
                    '      emit("trunc%d", t); }\n'
                    % (cstr(s.encode('utf-8')), cap, cap))
        # glyph index + advance for one character from every range
        f.write('    { uint32_t a;\n')
        for cp in (0x41, 0xC9, 0x3042, 0x30AB, 0x65E5, 0x266A, 0xFF21, 0x2019,
                   0x0416, 0x03A9, 0xAC00, 0x20AC):
            f.write('      hputs("glyph %d "); hputu(fb_resolve(%du, &a) & 0x3FFFFFFFu);'
                    ' hputc(\' \'); hputu(a); hputc(\'\\n\');\n' % (cp, cp))
        f.write('    }\n    MMIO_EXIT = 0;\n    return 0;\n}\n')

    elf = os.path.join(HERE, 'text.elf')
    cmd = [GCC, '-march=rv32im', '-mabi=ilp32', '-mno-relax', '-O2',
           '-ffreestanding', '-nostdlib', '-Wall',
           '-T', os.path.join(HERE, 'link.ld'),
           os.path.join(HERE, 'start.S'), gen, '-o', elf]
    r = subprocess.run(cmd, capture_output=True, text=True)
    if r.returncode:
        print(r.stdout + r.stderr)
        raise SystemExit('compile failed')
    if r.stderr.strip():
        print(r.stderr.strip())

    sim = subprocess.run([sys.executable, os.path.join(ROOT, 'tools', 'rv32sim.py'), elf],
                         capture_output=True, text=True)
    if sim.returncode:
        print(sim.stdout + sim.stderr)
        raise SystemExit('simulation failed')

    got = {}
    for line in sim.stdout.splitlines():
        if not line.strip():
            continue
        head, _, rest = line.partition(' ')
        got.setdefault(head, []).append(rest.strip())

    # ---- check the decoders --------------------------------------------
    fails = 0

    def decode(parts_):
        return bytes(int(x) for x in parts_.rstrip(',').split(',') if x != '')

    expect = {
        'utf8_kanji':     '\u5b87\u591a\u7530\u30d2\u30ab\u30eb',
        'utf8_ascii':     'Daft Punk',
        'utf16le_bom':    '\u521d\u604b',
        'utf16be_bom':    '\u521d\u604b',
        'utf16be_no_bom': '\u00c9dith',
        'latin1_bytes':   'Bj\u00f6rk',
        'cp1252_quotes':  'Rock \u201cn\u201d Roll \u2019s',
        'utf8_in_enc0':   '\u30d3\u30fc\u30eb',
        'surrogate_pair': '?ok',
    }
    for k, want in expect.items():
        raw = decode(got[k][0])
        ok = raw == want.encode('utf-8')
        print(('ok   ' if ok else 'FAIL ') + '%-16s %r' % (k, raw.decode('utf-8', 'replace')))
        fails += not ok

    raw = decode(got['bad_utf8_tail'][0])
    ok = raw.decode('utf-8', 'strict') if True else None
    try:
        raw.decode('utf-8')
        good = True
    except UnicodeDecodeError:
        good = False
    print(('ok   ' if good else 'FAIL ') + '%-16s %r (malformed input stays valid UTF-8)'
          % ('bad_utf8_tail', raw))
    fails += not good

    # ---- truncation ------------------------------------------------------
    for (s, cap), key in zip(TRUNC, ['trunc%d' % c for _, c in TRUNC]):
        raw = decode(got[key][0])
        try:
            txt = raw.decode('utf-8')
            valid = True
        except UnicodeDecodeError:
            valid = False
        fits = len(raw) <= cap - 1
        whole = s.startswith(txt) if valid else False
        ok = valid and fits and whole
        print(('ok   ' if ok else 'FAIL ') + '%-16s %d bytes, whole characters: %r'
              % (key, len(raw), txt if valid else raw))
        fails += not ok

    # ---- glyph indexes against the font file -----------------------------
    blob = open(os.path.join(ROOT, 'dist', 'Assets', 'mp3player', 'common',
                             'mp3font.bin'), 'rb').read()
    hdr = io.open(os.path.join(ROOT, 'fw', 'font_ext.h'), encoding='utf-8').read()
    ranges = [(int(a, 16), int(c), int(b, 16)) for a, c, b in
              re.findall(r'\{ 0x([0-9A-F]+),\s*(\d+),\s*0x([0-9A-F]+) \}', hdr)]
    N4, W4, W1, FMT1 = 1024, 64, 16, 1 << 17

    for line in got['glyph']:
        cp, idx, adv = (int(x) for x in line.split())
        if 0x20 <= cp <= 0x7E:                 # ASCII stays in the FPGA's ROM
            ok = idx == cp
            print(('ok   ' if ok else 'FAIL ') +
                  'glyph U+%04X -> ROM %d adv %d' % (cp, idx, adv))
            fails += not ok
            continue
        hit = next(((f, c, b) for f, c, b in ranges if f <= cp < f + c), None)
        if hit is None:
            ok = idx == ord('?')               # e.g. Hangul: not shipped
            print(('ok   ' if ok else 'FAIL ') +
                  'glyph U+%04X -> fallback %d' % (cp, idx))
            fails += not ok
            continue
        f, c, b = hit
        want = b + (cp - f)
        ok = idx == want
        # and the glyph really is non-blank in the file
        if b & FMT1:
            off = N4 * W4 * 2 + (want & ~FMT1) * W1 * 2
            ink = any(struct.unpack_from('<16H', blob, off))
        else:
            off = want * W4 * 2
            ink = any(struct.unpack_from('<64H', blob, off))
        print(('ok   ' if ok and ink else 'FAIL ') +
              'glyph U+%04X -> %#x adv %d, ink %s' % (cp, idx, adv, ink))
        fails += not (ok and ink)

    print('\n%s (%d failures)' % ('FAILED' if fails else 'PASSED', fails))
    return 1 if fails else 0


if __name__ == '__main__':
    raise SystemExit(main())
