#!/usr/bin/env python3
"""Checks the core's lrc_uslt_decode() against real USLT frames.

Same approach as lrc_check.py: the C is EXTRACTED from fw/lyrics.inc and run
under tools/rv32sim.py, so the thing under test is the shipping source and
cannot drift from it by being edited separately.

Worth testing rather than reasoning about, because USLT is the awkward frame:
after the encoding byte come three bytes of language and then a NUL-TERMINATED
DESCRIPTOR in the frame's own encoding -- a 16-bit terminator for UTF-16, with
the descriptor and the text each carrying their own BOM. The decoder also has
to WINDOW the body, since a 6 KB UTF-16 frame does not fit the 4 KB tag
buffer, and a window boundary must never split a code unit.

Input is the real frame out of a real file, and the expected output is that
same frame decoded independently in Python -- so a mistake in the C cannot be
mirrored by a matching mistake in the fixture.

    python tools/host/uslt_check.py <file.mp3> [...]
"""
import io, os, struct, subprocess, sys

sys.stdout.reconfigure(encoding='utf-8', errors='replace')

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.abspath(os.path.join(HERE, '..', '..'))


def extract(src, sig):
    i = src.index(sig)
    j = src.index('{', i)
    depth = 0
    for k in range(j, len(src)):
        if src[k] == '{':
            depth += 1
        elif src[k] == '}':
            depth -= 1
            if depth == 0:
                return src[i:k + 1]
    raise SystemExit('unbalanced braces extracting %s' % sig)


def syncsafe(b):
    return (b[0] & 0x7f) << 21 | (b[1] & 0x7f) << 14 | (b[2] & 0x7f) << 7 | (b[3] & 0x7f)


def uslt_body(path):
    """The USLT frame body, exactly as the firmware would see it."""
    with open(path, 'rb') as f:
        h = f.read(10)
        if h[:3] != b'ID3':
            return None
        ver, end, pos = h[3], 10 + syncsafe(h[6:10]), 10
        while pos + 10 <= end:
            f.seek(pos)
            fh = f.read(10)
            if len(fh) < 10 or not fh[0:1].isalnum():
                return None
            fsz = syncsafe(fh[4:8]) if ver >= 4 else struct.unpack('>I', fh[4:8])[0]
            if fh[:4] == b'USLT':
                return f.read(fsz)
            if fsz <= 0:
                return None
            pos += 10 + fsz
    return None


def expect(body):
    """Decode independently, so the fixture cannot share a bug with the C."""
    enc, r = body[0], body[1:]
    r = r[3:]                                   # language
    if enc in (1, 2):
        i = 0
        while i + 1 < len(r) and r[i:i + 2] != b'\x00\x00':
            i += 2
        t = r[i + 2:]
        return t.decode('utf-16' if enc == 1 else 'utf-16-be', 'replace')
    i = r.find(b'\x00')
    return r[i + 1:].decode('utf-8' if enc == 3 else 'latin-1', 'replace')


def run(body):
    inc = io.open(os.path.join(ROOT, 'fw', 'lyrics.inc'), encoding='utf-8').read()
    u8h = io.open(os.path.join(ROOT, 'fw', 'utf8.h'), encoding='utf-8').read()
    dec = extract(inc, 'static uint32_t lrc_uslt_decode')
    put = extract(u8h, 'static uint32_t u8_put')

    pc = io.open(os.path.join(ROOT, 'fw', 'player.c'), encoding='utf-8',
                 errors='replace').read()
    # Track the SHIPPING constant: a hardcoded copy here would hide exactly
    # the truncation behaviour this is meant to exercise.
    tmax = int(re.search(r'#define\s+LRC_TEXT_MAX\s+(\d+)', pc).group(1))

    gen = os.path.join(HERE, 'uslt_gen.c')
    with io.open(gen, 'w', encoding='utf-8', newline='\n') as f:
        f.write('/* GENERATED by uslt_check.py from fw/lyrics.inc. Do not edit. */\n')
        f.write('#include "hostio.h"\n\n')
        f.write('#define LRC_TEXT_MAX 3072u\n')
        f.write('#define TAG_SIZE     4096u\n')
        f.write('#define MP3_SLOT_ID  2u\n\n')
        f.write('#define TAG_OFF      0u\n')
        f.write('static char    lrc_text[LRC_TEXT_MAX];\n')
        f.write('static uint8_t tagbuf[TAG_SIZE];\n\n')
        f.write('static const unsigned char BODY[] = {\n')
        for i in range(0, len(body), 16):
            f.write('  ' + ','.join(str(c) for c in body[i:i + 16]) + ',\n')
        f.write('};\n')
        f.write('#define BODY_LEN %du\n\n' % len(body))
        # The file IS the frame body here, so a read is a bounded copy.
        f.write('static int target_read_slot(uint32_t slot, uint32_t off,\n'
                '                            uint32_t dst, uint32_t len)\n{\n'
                '    (void)slot; (void)dst;\n'
                '    if (off + len > BODY_LEN) return 0;\n'
                '    for (uint32_t i = 0; i < len; i++) tagbuf[i] = BODY[off + i];\n'
                '    return 1;\n}\n\n')
        f.write(put + '\n\n')
        f.write(dec + '\n\n')
        f.write('int main(void)\n{\n')
        f.write('    uint32_t n = lrc_uslt_decode(0, BODY_LEN);\n')
        f.write('    hputu(n); hnl();\n')
        f.write('    for (uint32_t i = 0; i < n; i++) hputc((unsigned char)lrc_text[i]);\n')
        f.write('    hnl();\n    return 0;\n}\n')

    gcc = os.path.join(ROOT, 'toolchain', 'xpack-riscv-none-elf-gcc-15.2.0-1',
                       'bin', 'riscv-none-elf-gcc.exe')
    elf = os.path.join(HERE, 'uslt.elf')
    r = subprocess.run([gcc, '-march=rv32im', '-mabi=ilp32', '-mno-relax', '-O2',
                        '-ffreestanding', '-nostdlib', '-nostartfiles',
                        '-T', os.path.join(HERE, 'link.ld'), '-o', elf,
                        os.path.join(HERE, 'start.S'), gen, '-lgcc'],
                       capture_output=True, text=True)
    if r.returncode:
        print(r.stderr)
        return None
    out = subprocess.run([sys.executable, os.path.join(ROOT, 'tools', 'rv32sim.py'), elf],
                         capture_output=True, text=True)
    if out.returncode:
        print(out.stderr)
        return None
    raw = out.stdout.split('\n', 1)
    return int(raw[0].strip()), raw[1].rstrip('\n')


def main(paths):
    ok = True
    for p in paths:
        body = uslt_body(p)
        print('=== %s' % os.path.basename(p))
        if not body:
            print('    no USLT frame'); ok = False; continue
        want = expect(body)
        got = run(body)
        if got is None:
            ok = False; continue
        n, text = got
        # The firmware truncates at LRC_TEXT_MAX; compare only that far.
        w = want.encode('utf-8')[:3071].decode('utf-8', 'ignore')
        match = text.startswith(w[:len(text)]) and len(text) > 0
        print('    frame %d B, enc %d -> %d bytes decoded, %d expected'
              % (len(body), body[0], n, len(want.encode('utf-8'))))
        print('    first line: %s' % text.splitlines()[0][:58] if text else '    (empty)')
        print('    %s' % ('MATCHES the independent decode'
                          if match else 'MISMATCH <-- see above'))
        ok &= match
    print()
    print('USLT DECODER OK' if ok else 'USLT DECODER FAULT')
    return 0 if ok else 1


sys.exit(main(sys.argv[1:]))
