#include "hostio.h"
#define TS_1X 0
#define FONT_CELL_W 16u
#define LRC_WRAP_MAX 3u
static const unsigned char ts_half[6]={2,3,4,6,3,4};
static const unsigned char font_adv[95]={4,5,9,12,11,15,13,6,7,6,10,11,6,8,5,8,11,7,10,10,12,10,11,10,11,11,5,5,11,11,12,10,16,14,11,13,12,10,10,13,12,5,10,12,10,15,12,13,11,13,12,11,12,12,13,16,13,12,11,7,8,6,9,9,6,10,11,11,11,11,8,11,10,5,5,11,5,15,10,11,11,11,8,10,7,10,11,15,11,11,10,8,6,7,11};
static uint32_t fb_adv(uint32_t cp,uint32_t sx){(void)sx;return (cp>=32u&&cp<32u+95u)?font_adv[cp-32u]:font_adv[31];}
static uint32_t u8_next(const char **p)
{
    const unsigned char *s = (const unsigned char *)*p;
    uint32_t c = s[0], n;
    if (c < 0x80u) { *p += 1; return c; }
    if      (c >= 0xC2u && c <= 0xDFu) { n = 1u; c &= 0x1Fu; }
    else if (c >= 0xE0u && c <= 0xEFu) { n = 2u; c &= 0x0Fu; }
    else if (c >= 0xF0u && c <= 0xF4u) { n = 3u; c &= 0x07u; }
    else { *p += 1; return '?'; }
    for (uint32_t i = 1; i <= n; i++) {
        if ((s[i] & 0xC0u) != 0x80u) { *p += 1; return '?'; }
        c = (c << 6) | (s[i] & 0x3Fu);
    }
    *p += n + 1u;
    return c;
}
static uint32_t lrc_maxw(uint32_t ww)
{
    uint32_t cell = (FONT_CELL_W * ts_half[TS_1X]) / 2u;
    return (ww > cell) ? ww - cell : ww;
}
static uint32_t lrc_wrap(const char *s, uint32_t ww, uint16_t *st)
{
    uint32_t mx = lrc_maxw(ww);
    uint32_t n = 1u, i = 0, w = 0, sp = 0, start = 0;
    st[0] = 0;
    while (s[i]) {
        /* CODE POINTS, not bytes. Measuring per byte made a 3-byte kana
         * count as three Latin advances -- a Japanese sheet measured 270
         * px where it paints 144 -- so 26 of 44 lines wrapped when 4
         * needed to, and the break landed INSIDE a sequence 13 times,
         * which draws as garbage. i is always a character boundary, so
         * breaking there is safe. */
        const char *p = s + i;
        uint32_t cp  = u8_next(&p);
        uint32_t nxt = (uint32_t)(p - s);
        if (cp == ' ') sp = i;
        w += fb_adv(cp, TS_1X);
        if (w > mx && n < LRC_WRAP_MAX) {
            uint32_t b = (sp > start) ? sp : i;
            while (s[b] == ' ') b++;          /* next row starts after it */
            /* A single glyph wider than the box would otherwise break at
             * the same place forever. Step past THIS character, which
             * keeps the offset on a boundary. */
            if (b <= start) b = nxt;
            st[n++] = (uint16_t)b;
            start = b; i = b; w = 0; sp = 0;
            continue;
        }
        i = nxt;
    }
    return n;
}
static const char *L[]={
"I'm going for a walk",
"Not the after dinner kind",
"I'm gonna use my hands",
"And I'm gonna use my mind",
"And who the hell are you",
"To tell me what to do?",
"You can't even tie your own haggard shoes",
"Your closet is a mess,",
"And your backyard's falling down",
"And I have no grand ideas or intentions of sticking around",
"So I'm going for a walk",
"Not the after dinner kind",
"I'm gonna use my hands",
"And I'm gonna use my mind",
"I'm gonna build a world",
"Independent and exempt",
"All alone I'll be an empire",
"With no mortgage and no rent",
"And I don't need to live in your stinking zoo",
"You can't even feed the animals donated to you",
"Your storage sheds are ramshackled, flies decorate the walls",
"And you expect me to die here in this shit filled tiny stall?",
"I'm going for a walk",
"And I know you're watching! everything I do",
"Call me threat to your children call me socially unglued",
"Call me master of insanity, unable to relate",
"Call me lazy, bane, and filthy",
"Call me monstrous reprobate",
"I'm going for a walk",
"And there's nothing you can do",
"'Cuz I don't have to",
"Live like you",
"So I'm going for a walk",
"Galaxie - Blind Melon",
"Is this the place that I want to be",
"Is it you who I want to see",
"Holdin' on, hold it high, show me everything",
"And you're leavin' me, yeah you're leavin' me",
"you're leaving me with a hated identity",
"But I keep only comin' here and standing in this state",
"Oh and I'm never really sure if you'll take what I'm saying the right way",
"But I'm not appalled or afraid verbal pocket play",
"Is as discreet as I can muster up to be",
"Because the Cadillac that's sittin' in the back",
"It isn't me",
"Oh, no, no, no it isn't me",
"I'm more at home in my galaxie Oh Yeah",
"Can I do the things I wanna do",
"That I don't do because of you",
"And I'll take a left and I'll second",
"guess into total mess",
"And you're leaving me",
"Yeah you're leaving me",
"you're leaving me with a hated identity",
"But I keep on a comin' here and standing in this state",
"Oh and I'm always reassured the situation's gettin' carried away",
"But I'm not appalled or afraid verbal pocket play",
"Is as discreet as I can muster up to be",
"Because mah Cadillac that's sittin' in the back",
"It isn't me",
"No no no no it isn't me",
"Woah no no no it isn't me",
"No it isn't me",
"No it isn't me",
"No it isn't me",
"Woah no it isn't me",
"No it isn't me",
"in my galaxie",
"I want to live where soul meets body",
"And let the sun wrap its arms around me",
"And bathe my skin in water cool and cleansing",
"And feel, feel what its like to be new",
"Cause in my head there's a greyhound station",
"Where I send my thoughts to far off destinations",
"So they may have a chance of finding a place",
"Where they're far more suited than here",
"And I cannot guess what we'll discover",
"When we turn the dirt with our palms cupped like shovels",
"But I know our filthy hands can wash one another's",
"And not one speck will remain",
"And I do believe it's true",
"That there are roads left in both of our shoes",
"But if the silence takes you",
"Then I hope it takes me too",
"So brown eyes I hold you near",
"Cause you're the only song I want to hear",
"A melody softly soaring through my atmosphere",
"Where soul meets body",
"Where soul meets body",
"Where soul meets body",
"And I do believe it's true",
"That there are roads left in both of our shoes",
"But if the silence takes you",
"Then I hope it takes me too",
"So brown eyes I hold you near",
"Cause you're the only song I want to hear",
"A melody softly soaring through my atmosphere",
"A melody softly soaring through my atmosphere",
"A melody softly soaring through my atmosphere",
"A melody softly soaring through my atmosphere",
"You get a shiver in the dark, it's raining in the park, but meantime",
"South of the river, you stop and you hold everything",
"A band is blowing Dixie, double-four time",
"You feel alright when you hear that music ring",
"Well, now you step inside, but you don't see too many faces",
"Coming in out of the rain to hear the jazz go down",
"Competition in other places",
"Ah, but the horns, they blowing that sound",
"Way on down south",
"Way on down south, London town",
"You check out Guitar George, he knows all the chords",
"Mind, he's strictly rhythm, he doesn't want to make it cry or sing",
"Yes and an old guitar is all he can afford",
"When he gets up under the lights to play his thing",
"And Harry doesn't mind if he doesn't make the scene",
"He's got a daytime job, he's doing alright",
"He can play the honky-tonk like anything",
"Saving it up for Friday night",
"With the Sultans",
"With the Sultans of Swing",
"And a crowd of young boys, they're fooling around in the corner",
"Drunk and dressed in their best brown baggies and their platform soles",
"They don't give a damn about any trumpet-playing band",
"It ain't what they call rock and roll",
"And the Sultans",
"Yeah, the Sultans, they played creole",
"Creole",
"And then the man, he steps right up to the microphone",
"And says at last, just as the time bell rings",
"\"Goodnight, now it's time to go home\"",
"Then he makes it fast with one more thing",
"\"We are the Sultans",
"We are the Sultans of Swing\"",
"Feel good",
"Sha, sha-ba-da, sha-ba-da-ca, feel good",
"Sha, sha-ba-da, sha-ba-da-ca, feel good",
"Sha, sha-ba-da, sha-ba-da-ca, feel good",
"Sha, sha-ba-da, sha-ba-da-ca, feel good",
"Sha, sha-ba-da, sha-ba-da-ca, feel good",
"Sha, sha-ba-da, sha-ba-da-ca, feel good",
"Sha, sha-ba-da, sha-ba-da-ca, feel good",
"Sha, sha-ba-da, sha-ba-da-ca, feel good",
"City's breaking down on a camel's back",
"They just have to go, 'cause they don't know wack",
"So while you fill the streets, it's appealing to see",
"You won't get out the county, 'cause you're bad and free",
"You got a new horizon, it's ephemeral style",
"A melancholy town where we never smile",
"And all I wanna hear is the message beep",
"My dreams, they got a kissing",
"'Cause I don't get sleep, no",
"Windmill, windmill for the land",
"Turn forever hand in hand",
"Take it all in on your stride",
"It is ticking, falling down",
"Love forever, love is freely",
"Turned forever, you and me",
"Windmill, windmill for the land",
"Is everybody in?",
"Laughin' gas these hazmats, fast cats",
"Linin' 'em up like ass cracks",
"Play these ponies at the track",
"It's my chocolate attack",
"Shit, I'm steppin' in the heart of this here (yeah)",
"Care Bear rappin' in harder this year (yeah)",
"Watch me as I gravitate, ha-ha-ha-ha-ha",
"Yo, we gon' ghost town this Motown",
"With yo' sound, you in the blink",
"Gon' bite the dust, can't fight with us",
"With yo' sound, you kill the Inc",
"So don't stop, get it, get it (get it)",
"Until you're cheddar headed",
"And watch the way I navigate",
"Ha-ha-ha-ha-ha",
"Sha, sha-ba-da, sha-ba-da-ca, feel good",
"Sha, sha-ba-da, sha-ba-da-ca, feel good",
"Sha, sha-ba-da, sha-ba-da-ca, feel good",
"Sha, sha-ba-da, sha-ba-da-ca, feel good",
"Windmill, windmill for the land",
"Turn forever hand in hand",
"Take it all in on your stride",
"It is ticking, falling down",
"Love forever, love is freely",
"Turned forever, you and me",
"Windmill, windmill for the land",
"Is everybody in?",
"Don't stop, get it, get it (sha, sha-ba-da)",
"Peep how your captain's in it (sha-ba-da-ca, feel good)",
"Steady, watch me navigate (sha, sha-ba-da)",
"Ha-ha-ha-ha-ha (sha-ba-da-ca, feel good)",
"Don't stop, get it, get it (sha, sha-ba-da)",
"Peep how your captain's in it (sha-ba-da-ca, feel good)",
"Steady, watch me navigate (sha, sha-ba-da)",
"Ha-ha-ha-ha-ha (sha-ba-da-ca, feel good)",
"Sha, sha-ba-da, sha-ba-da-ca, feel good",
"Sha, sha-ba-da, sha-ba-da-ca, feel good",
"Sha, sha-ba-da, sha-ba-da-ca, feel good",
"Sha, sha-ba-da, sha-ba-da-ca, feel good",
"Well, Daft Punk is playing at my house, my house",
"I'll show you the ropes kid, show you the ropes",
"I got a bus and a trailer at my house, my house",
"I'll show you the ropes kid, show you the ropes",
"I bought fifteen cases for my house, my house",
"All the furniture is in the garage",
"Well, Daft Punk is playing at my house, my house",
"You got to set them up kid, set them up",
"You got to set 'em up (ooh, ooh, yeah)",
"You got to set 'em up (ooh, ooh, yeah)",
"You've got to set them up, set them up",
"Well, Daft Punk is playing at my house, my house",
"I waited for seven years and fifteen days",
"There's every kid for miles at my house, my house",
"And the neighbors can't call the police",
"There's a fist fight brewin' in my house, my house",
"Because the jocks can't get in the door",
"When Daft Punk is playing in my house, my house",
"You got to set them up kid, set them up",
"You've gotta set 'em up (ooh, ooh, yeah)",
"Got to set 'em up (ooh, ooh, yeah)",
"You got to set them up, set them up",
"You got to set 'em up (ooh, ooh, yeah)",
"You got to set 'em up (ooh, ooh, yeah)",
"You got to set them up, set them up",
"(Solo)",
"Well, everybody's lined up in my house, my house",
"And Sarah's girlfriend is working the door",
"Got everybody's PA in my house, my house",
"All the robots descend from the bus",
"There's a freak out brewin' in my house, my house",
"In the basement",
"'Cause Daft Punk is playing at my house, my house",
"You got to set them up kid, set them up",
"You got to set 'em up (ooh, ooh, yeah)",
"You got to set 'em up (ooh, ooh, yeah)",
"You got to set them up, set them up",
"You got to set 'em up (ooh, ooh, yeah)",
"You got to set 'em up (ooh, ooh, yeah)",
"You got to set them up, set them up",
"And never, never let them go",
"No never, never, never let them go",
"Oh, never, never, never let them go",
"Let 'em go",
"Never, never, never let them go",
"Oh, never, never, never let them go",
"Oh, never, never, never let them go",
"Let them go",
"Downtown",
"I'm walking, I'm a southern stream",
"Get to the river 'fore I run too low",
"I'm walking, I'm a southern stream",
"Get to the river 'fore I run too low",
"Old gypsy woman spoke to me",
"Lips stained red from a bottle of wine",
"Old gypsy woman spoke to me",
"Lips stained red from a bottle of wine",
"The one that you are looking for",
"You're not gonna find her here",
"The one that you are looking for",
"You're not gonna find her here, here",
"I'm runnin', I'm a northeast stream",
"Get to the ocean 'fore I run too low",
"I'm runnin', I'm a northeast stream",
"Get to the ocean 'fore I run too low",
"Get to the ocean 'fore I run too low",
"The one that you are looking for",
"You're not gonna find her here",
"The one that you are looking for",
"You're not gonna find her here, here",
"Old gypsy woman spoke to me, said",
"You're a wolf, boy, get out of this town",
"Old gypsy woman spoke to me, said",
"You're a wolf, boy, get out of this town",
"You're a wolf, boy, get out of this town",
"You're a wolf, boy, get out of this town",
"You're a wolf",
"You're a wolf",
"You're a wolf",
"You're a wolf",
"Waiting",
"On a Sunday afternoon",
"For what I read between the lines",
"Your lies",
"Feelin'",
"Like a hand in rusted shame",
"So do you laugh or does it cry",
"Reply",
"Leavin' on a southern train",
"Only yesterday you lied",
"Promises of what I seemed to be",
"Only watched the time go by",
"All of these things you've said to me",
"Breathing",
"Is the hardest thing to do",
"With all I've said and all that's dead for you",
"You lied",
"Goodbye",
"Leavin' on a southern train",
"Only yesterday",
"You lied",
"Promises of what I seemed to be",
"Only watched the time go by",
"All of these things I've said to you",
"ドブネズミみたいに",
"美しくなりたい",
"写真には写らない",
"美しさがあるから",
"リンダリンダ",
"リンダリンダリンダ",
"リンダリンダ",
"リンダリンダリンダ",
"もしも僕がいつか君と出会い話し合うなら",
"そんな時はどうか愛の意味を知って下さい",
"リンダリンダ",
"リンダリンダリンダ",
"リンダリンダ",
"リンダリンダリンダ",
"ドブネズミみたいに",
"誰よりもやさしい",
"ドブネズミみたいに",
"何よりもあたたかく",
"リンダリンダ",
"リンダリンダリンダ",
"リンダリンダ",
"リンダリンダリンダ",
"もしも僕がいつか君と出会い話し合うなら",
"そんな時はどうか愛の意味を知って下さい",
"愛じゃなくても",
"恋じゃなくても",
"君を離しはしない",
"決して負けない",
"強い力を",
"僕は一つだけ持つ",
"リンダリンダ",
"リンダリンダリンダ",
"リンダリンダ",
"リンダリンダリンダ",
"リンダリンダ",
"リンダリンダリンダ",
"リンダリンダ",
"リンダリンダリンダ",
"リンダリンダ",
"リンダリンダリンダ",
"リンダリンダ",
"リンダリンダリンダ",
"リンダリンダ",
"リンダリンダリンダ",
"The only one I know, has come to take me away",
"The only one I know, is mine when she stitches me",
"The only one I see, has found an aching in me",
"The only one I see, has turned her tongue into me",
"Everyone has been burned before",
"Everybody knows the pain",
"The only one I know, never cries, never opens her eyes",
"The only one I know, wide awake and then she's away",
"The only one I see, is mine when she walks down the street",
"The only one I see, has carved her way into me",
"Everyone has been burned before",
"Everybody knows the pain",
"Everyone has been burned before",
"Everybody knows the pain",
"Everyone has been burned before",
"Everybody knows the pain",
"Everyone has been burned before",
"Everybody knows the pain",
};
#define NL 364u
int main(void){ uint32_t wws[2]={252u,360u};
 for(int q=0;q<2;q++){ uint32_t ww=wws[q]; uint32_t bad=0;
  for(uint32_t i=0;i<NL;i++){ const char*s=L[i]; uint16_t st[LRC_WRAP_MAX];
   uint32_t n=lrc_wrap(s,ww,st); uint32_t len=0; while(s[len])len++;
   for(uint32_t k=0;k<n;k++){ uint32_t a=st[k], b=(k+1<n)?st[k+1]:len;
    while(b>a&&s[b-1]==32)b--; if(b<=a)continue;
    uint32_t w=0,last=0; const char*q=s+a;
    while((uint32_t)(q-s)<b){last=fb_adv(u8_next(&q),0);w+=last;}
    uint32_t pw=w+((16u>last)?(16u-last):0u); if(pw>ww){bad++;}
    if(a>0 && ((unsigned char)s[a]&0xC0u)==0x80u){bad++;}
   } }
  hputu(ww);hputc(32);hputu(bad);hnl(); }
 return 0;}
