/* GENERATED by tools/gen_eq_coeffs.py --curves -- DO NOT EDIT.
 *
 * Each preset's response drawn on the meter, 36 bars wide, as a
 * SIGNED offset from the centre line in pixels: boost above, cut
 * below, clamped to +/-8 dB over +/-35 px.
 *
 * Generated from the same quantised coefficients the RTL filters
 * with, so what is on screen is the filter's real response and
 * cannot drift from it. Deliberately WITHOUT the preamp: that is a
 * level adjustment, and the tonal shape is what is being shown.
 */
#define EQ_CURVE_N 36
#define EQ_COUNT   8

static const signed char eq_curve[EQ_COUNT][EQ_CURVE_N] = {
    {   0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0 },   /* FLAT */
    {  20, 20, 20, 20, 19, 18, 17, 15, 13, 12, 11, 12, 15, 15, 12,  8,  5,  3,  2,  1,  1,  0,  0, -1, -2, -3, -4, -4, -3, -2, -1, -1,  0,  0,  0,  0 },   /* BASS */
    {  26, 25, 24, 23, 21, 19, 16, 12, 10,  8,  7,  8,  9,  9,  6,  4,  1, -2, -4, -7, -8, -6, -3, -1,  2,  5,  7,  9,  8,  6,  5,  6,  8, 11, 15, 17 },   /* ROCK */
    {  -5, -5, -5, -4, -4, -4, -3, -2, -1, -1,  0,  0,  0,  1,  1,  2,  2,  4,  6,  9, 10,  9,  7,  6,  7, 10, 13, 14, 11,  8,  5,  4,  3,  3,  4,  4 },   /* POP */
    {  11, 11, 11, 11, 10, 10,  9,  7,  6,  5,  5,  5,  5,  5,  4,  3,  2,  1,  1,  0,  0,  0, -1, -1, -2, -3, -4, -4, -3, -1,  0,  1,  3,  5,  7,  8 },   /* JAZZ */
    {   0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  1,  1,  1,  2,  4,  6,  7,  8 },   /* CLASSICAL */
    {  -9, -9, -9, -9, -9, -9, -8, -7, -6, -4, -4, -4, -4, -4, -3, -1,  2,  4,  8, 12, 13, 11,  9,  7,  6,  7,  9,  9,  8,  5,  3,  2,  1,  0,  0,  0 },   /* VOCAL */
    {   0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  1,  1,  2,  2,  4,  6,  8, 10,  9,  7,  7,  8, 12, 17, 22, 25 },   /* TREBLE */
};

static const char *const eq_name[EQ_COUNT] = {
    "FLAT", "BASS", "ROCK", "POP", "JAZZ", "CLASSICAL", "VOCAL", "TREBLE"
};
