/* GENERATED by tools/gen_font_rom.py -- DO NOT EDIT. */
#ifndef FONT_METRICS_H
#define FONT_METRICS_H

#define FONT_FIRST 0x20u
#define FONT_LAST  0x7Eu
#define FONT_CELL_W 16u
#define FONT_CELL_H 16u

/* Per-glyph advance in source pixels. Glyphs are left-aligned in the cell,
 * so advancing by this overwrites only blank padding of the glyph before. */
static const unsigned char font_adv[95] = {
     4,  5,  9, 12, 11, 15, 13,  6,  7,  6, 10, 11,  6,  8,  5,  8,
    11,  7, 10, 10, 12, 10, 11, 10, 11, 11,  5,  5, 11, 11, 12, 10,
    16, 14, 11, 13, 12, 10, 10, 13, 12,  5, 10, 12, 10, 15, 12, 13,
    11, 13, 12, 11, 12, 12, 13, 16, 13, 12, 11,  7,  8,  6,  9,  9,
     6, 10, 11, 11, 11, 11,  8, 11, 10,  5,  5, 11,  5, 15, 10, 11,
    11, 11,  8, 10,  7, 10, 11, 15, 11, 11, 10,  8,  6,  7, 11,
};

#endif
