#!/usr/bin/env python3
"""Generate the 4bpp anti-aliased font ROM + C metrics from Inter (SIL OFL).

Replaces the 8x8 1-bit font that was upscaled with EPX. EPX gives crisp
diagonals but it is still a bitmap font pretending to be bigger than it is --
the result reads as "terminal", not "designed". Rendering a real typeface at
the target size with genuine greyscale coverage is what makes text look
drawn rather than plotted.

Layout, chosen to suit the hardware rather than the tooling:
  * CELL_H rows per glyph, CELL_W columns, 4 bits of coverage per pixel.
  * Packed 8 pixels per 32-bit word, so one source ROW is exactly 2 words --
    the engine fetches a row into a register and then has all its pixels
    combinationally. Addressing is glyph*ROW_WORDS*CELL_H + row*2 + half.
  * Glyphs are LEFT-ALIGNED in the cell and carry a per-glyph advance. The
    engine paints the whole cell including background, so the next glyph's
    cell must overwrite only blank padding -- left-aligning and advancing by
    the ink width keeps that true, which is what allows proportional spacing
    without needing a transparent blit.
"""
import sys
from pathlib import Path
from PIL import Image, ImageDraw, ImageFont

ROOT = Path(__file__).resolve().parent.parent
TTF = ROOT / "third_party" / "font" / "Inter-SemiBold.ttf"
ROM = ROOT / "src" / "fpga" / "core" / "font_rom.v"
HDR = ROOT / "fw" / "font_metrics.h"

FIRST, LAST = 0x20, 0x7E
NGLYPH = LAST - FIRST + 1
CELL_W, CELL_H = 16, 16
ROW_WORDS = CELL_W // 8          # 8 px per 32-bit word at 4bpp
WORDS_PER_GLYPH = ROW_WORDS * CELL_H

font = ImageFont.truetype(str(TTF), 15)
try:
    font.set_variation_by_axes([14.0, 600.0])   # opsz, wght -> SemiBold
except Exception:
    pass

# Common baseline so glyphs sit on one line rather than each being centred.
asc, desc = font.getmetrics()
baseline = 12   # leaves 4 rows for descenders inside the 16-row cell

words = []
advance = []
for code in range(FIRST, LAST + 1):
    ch = chr(code)
    img = Image.new("L", (CELL_W, CELL_H), 0)
    ImageDraw.Draw(img).text((0, baseline), ch, font=font, fill=255, anchor="ls")
    px = img.load()

    # Ink extent decides the advance; a space has none, so fall back to the
    # font's own advance for it.
    right = 0
    for x in range(CELL_W):
        for y in range(CELL_H):
            if px[x, y] > 8:
                right = max(right, x + 1)
                break
    adv = right + 2 if right else max(3, int(font.getlength(ch)))
    advance.append(min(adv, CELL_W))

    for y in range(CELL_H):
        for half in range(ROW_WORDS):
            w = 0
            for i in range(8):
                x = half * 8 + i
                # 8-bit -> 4-bit coverage, ROUNDED. ">> 4" was wrong at both
                # ends: it saturates from 240 up, so near-solid pixels rendered
                # as fully solid, and it floors everything under 16 to zero, so
                # the faintest edge coverage was DELETED. Those faint pixels are
                # what the eye integrates into a smooth stem edge; dropping them
                # is what made the type look harsh next to its own anti-aliasing.
                cov = (px[x, y] * 15 + 127) // 255
                w |= (cov & 0xF) << (i * 4)
            words.append(w)

assert len(words) == NGLYPH * WORDS_PER_GLYPH

out = [
    "// ==========================================================================",
    "// font_rom.v -- GENERATED by tools/gen_font_rom.py. DO NOT EDIT.",
    "//",
    "// Inter (SIL Open Font License 1.1), rendered to a 4-bit-per-pixel coverage",
    f"// atlas: {NGLYPH} glyphs, {CELL_W}x{CELL_H} cell, 8 px per 32-bit word.",
    "// Address = (glyph - 0x20)*%d + row*%d + half." % (WORDS_PER_GLYPH, ROW_WORDS),
    "//",
    "// 4bpp rather than 1bpp because the coverage value IS the anti-aliasing:",
    "// the engine blends fg->bg by it directly, so there is no EPX step and no",
    "// bitmap-font look to disguise.",
    "// ==========================================================================",
    "",
    "`default_nettype none",
    "",
    "module font_rom (",
    "    input  wire        clk,",
    "    input  wire [11:0] addr,",
    "    output reg  [31:0] q",
    ");",
    "",
    '    (* ramstyle = "M10K" *) reg [31:0] mem [0:%d];' % (len(words) - 1),
    "",
    "    initial begin",
]
for i, w in enumerate(words):
    out.append("        mem[%4d] = 32'h%08X;" % (i, w))
out += [
    "    end",
    "",
    "    always @(posedge clk) q <= mem[addr];",
    "",
    "endmodule",
    "",
    "`default_nettype wire",
    "",
]
ROM.write_text("\n".join(out))

hdr = [
    "/* GENERATED by tools/gen_font_rom.py -- DO NOT EDIT. */",
    "#ifndef FONT_METRICS_H",
    "#define FONT_METRICS_H",
    "",
    "#define FONT_FIRST 0x%02Xu" % FIRST,
    "#define FONT_LAST  0x%02Xu" % LAST,
    "#define FONT_CELL_W %du" % CELL_W,
    "#define FONT_CELL_H %du" % CELL_H,
    "",
    "/* Per-glyph advance in source pixels. Glyphs are left-aligned in the cell,",
    " * so advancing by this overwrites only blank padding of the glyph before. */",
    "static const unsigned char font_adv[%d] = {" % NGLYPH,
]
for i in range(0, NGLYPH, 16):
    hdr.append("    " + ", ".join("%2d" % a for a in advance[i:i + 16]) + ",")
hdr += ["};", "", "#endif", ""]
HDR.write_text("\n".join(hdr))

print("glyphs=%d words=%d rom=%.0fKB (%d M10K)"
      % (NGLYPH, len(words), len(words) * 4 / 1024, (len(words) * 32 + 10239) // 10240))
print("advance range: %d..%d" % (min(advance), max(advance)))
