#!/usr/bin/env python3
"""Builds a set of tiny MP3s whose TAGS are the test, one per script.

The point is to see the font and the tag decoders working across everything
the core claims to support -- in the playlist browser AND on the player card --
without needing real music in twelve languages. So the audio is silence
(valid MPEG-1 Layer III frames with empty side info) and all the interest is
in the ID3 frames.

The ENCODINGS are varied deliberately, because that is the other half of what
can go wrong: a tagger writing UTF-16 and a tagger writing UTF-8 exercise
different paths in id3_text_body(), and encoding 0 exercises the guess between
Windows-1252 and UTF-8-written-into-a-Latin-1-field.

Two entries are expected to FAIL, and are here on purpose: Korean has no glyphs
in the font, and Vietnamese has only some. They should show '?' rather than
anything alarming.

    python tools/make_lang_tests.py [--out DIR]
"""
import argparse
import io
import os

# MPEG-1 Layer III, 44.1 kHz, 64 kbps, mono. Side info and main data left zero,
# which every decoder renders as silence.
HDR = bytes((0xFF, 0xFB, 0x50, 0xC4))
FRAME = 208
SECONDS = 8
FRAMES = int(SECONDS * 44100 / 1152)


def silence():
    return (HDR + bytes(FRAME - len(HDR))) * FRAMES


def text_frame(fid, text, enc):
    """enc 0 = Latin-1/1252, 1 = UTF-16 with BOM, 3 = UTF-8."""
    if enc == 1:
        body = b'\x01\xff\xfe' + text.encode('utf-16-le') + b'\x00\x00'
    elif enc == 3:
        body = b'\x03' + text.encode('utf-8') + b'\x00'
    else:
        body = b'\x00' + text.encode('cp1252', 'replace') + b'\x00'
    return fid + len(body).to_bytes(4, 'big') + b'\x00\x00' + body


def tag(title, artist, album, enc, major=3):
    body = b''.join([text_frame(b'TIT2', title, enc),
                     text_frame(b'TPE1', artist, enc),
                     text_frame(b'TALB', album, enc),
                     text_frame(b'TRCK', '1', 0)])
    body += b'\x00' * 64
    sz = len(body)
    ss = bytes(((sz >> 21) & 0x7F, (sz >> 14) & 0x7F, (sz >> 7) & 0x7F, sz & 0x7F))
    return b'ID3' + bytes((major, 0, 0)) + ss + body


#  file stem                  title                       artist                 album                    enc
TESTS = [
    ("01-japanese",     "初恋",                   "宇多田ヒカル",
                        "Fantome",                                                                          1),
    ("02-japanese-kana","リンダ リンダ", "ブルーハーツ",
                        "ハイキック！",                                             3),
    ("03-chinese",      "月亮代表我的心", "邓丽君",
                        "小城故事",                                                         3),
    ("04-greek",        "Το Φεγγάρι",
                        "Χατζιδάκις",
                        "Ελληνικά",                                 1),
    ("05-cyrillic",     "Группа крови",
                        "Кино", "Звезда",                 1),
    ("06-polish",       "Dziwny jest ten świat", "Czesław Niemen",
                        "Dziwny jest ten świat",                                                       3),
    ("07-czech",        "Příliš žluťoučký kůň",
                        "Škoda", "České písně",                                    3),
    ("08-turkish",      "Güneşi Beklerken", "Şebnem Ferah", "Perde",                         3),
    ("09-french-caps",  "Non, je ne regrette rien", "Édith Piaf", "À l'Olympia",                  0),
    ("10-nordic",       "Jóga", "Björk", "Homogenic",                                             0),
    ("11-symbols",      "Rock ’n’ Roll — ♪ ★ ½ €",
                        "Smart “Quotes”", "Punctuation …",                                   1),
    ("12-korean-x",     "봄날", "방탄소년단", "Not in the font",                3),
    ("13-vietnamese-x", "Diễm Xưa", "Trịnh Công Sơn", "Partial",                   3),
]


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--out', default='LangTest')
    ap.add_argument('--playlist', default='test.m3u')
    a = ap.parse_args()

    os.makedirs(a.out, exist_ok=True)
    audio = silence()
    lines = ["# Language / tag test set -- generated by tools/make_lang_tests.py",
             "# Silent audio on purpose: the TAGS are what is being looked at."]
    for stem, title, artist, album, enc in TESTS:
        name = stem + ".mp3"
        with open(os.path.join(a.out, name), 'wb') as f:
            f.write(tag(title, artist, album, enc, 4 if enc == 3 else 3))
            f.write(audio)
        lines.append("%s/%s" % (os.path.basename(a.out), name))
    io.open(a.playlist, 'w', encoding='utf-8', newline='\n').write("\n".join(lines) + "\n")

    total = sum(os.path.getsize(os.path.join(a.out, s + ".mp3")) for s, *_ in TESTS)
    print("%d files, %.0f KB total, %s and %s"
          % (len(TESTS), total / 1024, a.out, a.playlist))
    for stem, title, artist, album, enc in TESTS:
        kind = {0: 'Latin-1/1252', 1: 'UTF-16', 3: 'UTF-8'}[enc]
        print("   %-18s %-10s %s — %s" % (stem, kind, artist, title))


if __name__ == '__main__':
    main()
