// GENERATED by tools/gen_eq_coeffs.py --verilog -- DO NOT EDIT.
//
// Q2.16 signed (18-bit), Fs = 48000 Hz. Five bands per preset,
// five coefficients per band, in the order b0 b1 b2 a1 a2.
// Index: ((preset*5) + band)*5 + k
//
// The difference equation SUBTRACTS a1 and a2:
//   y = b0*x + b1*x1 + b2*x2 - a1*y1 - a2*y2

// ---- FLAT (preset 0), preamp -0.00 dB
//   lowshelf      80 Hz
crom[  0] = 18'sd65536  ;  // b0
crom[  1] = -18'sd129915;  // b1
crom[  2] = 18'sd64386  ;  // b2
crom[  3] = -18'sd129915;  // a1
crom[  4] = 18'sd64386  ;  // a2
//   peak         250 Hz
crom[  5] = 18'sd65536  ;  // b0
crom[  6] = -18'sd128893;  // b1
crom[  7] = 18'sd63426  ;  // b2
crom[  8] = -18'sd128893;  // a1
crom[  9] = 18'sd63426  ;  // a2
//   peak        1000 Hz
crom[ 10] = 18'sd65536  ;  // b0
crom[ 11] = -18'sd121989;  // b1
crom[ 12] = 18'sd57506  ;  // b2
crom[ 13] = -18'sd121989;  // a1
crom[ 14] = 18'sd57506  ;  // a2
//   peak        4000 Hz
crom[ 15] = 18'sd65536  ;  // b0
crom[ 16] = -18'sd90809 ;  // b1
crom[ 17] = 18'sd39322  ;  // b2
crom[ 18] = -18'sd90809 ;  // a1
crom[ 19] = 18'sd39322  ;  // a2
//   highshelf  12000 Hz
crom[ 20] = 18'sd65536  ;  // b0
crom[ 21] = 18'sd0      ;  // b1
crom[ 22] = 18'sd5500   ;  // b2
crom[ 23] = 18'sd0      ;  // a1
crom[ 24] = 18'sd5500   ;  // a2
// ---- BASS (preset 1), preamp -1.87 dB
//   lowshelf      80 Hz
crom[ 25] = 18'sd65739  ;  // b0
crom[ 26] = -18'sd130087;  // b1
crom[ 27] = 18'sd64358  ;  // b2
crom[ 28] = -18'sd130089;  // a1
crom[ 29] = 18'sd64559  ;  // a2
//   peak         250 Hz
crom[ 30] = 18'sd65903  ;  // b0
crom[ 31] = -18'sd129223;  // b1
crom[ 32] = 18'sd63389  ;  // b2
crom[ 33] = -18'sd129223;  // a1
crom[ 34] = 18'sd63756  ;  // a2
//   peak        1000 Hz
crom[ 35] = 18'sd65536  ;  // b0
crom[ 36] = -18'sd121989;  // b1
crom[ 37] = 18'sd57506  ;  // b2
crom[ 38] = -18'sd121989;  // a1
crom[ 39] = 18'sd57506  ;  // a2
//   peak        4000 Hz
crom[ 40] = 18'sd64044  ;  // b0
crom[ 41] = -18'sd89746 ;  // b1
crom[ 42] = 18'sd39586  ;  // b2
crom[ 43] = -18'sd89746 ;  // a1
crom[ 44] = 18'sd38094  ;  // a2
//   highshelf  12000 Hz
crom[ 45] = 18'sd65536  ;  // b0
crom[ 46] = 18'sd0      ;  // b1
crom[ 47] = 18'sd5500   ;  // b2
crom[ 48] = 18'sd0      ;  // a1
crom[ 49] = 18'sd5500   ;  // a2
// ---- ROCK (preset 2), preamp -2.24 dB
//   lowshelf      80 Hz
crom[ 50] = 18'sd65704  ;  // b0
crom[ 51] = -18'sd130061;  // b1
crom[ 52] = 18'sd64367  ;  // b2
crom[ 53] = -18'sd130064;  // a1
crom[ 54] = 18'sd64533  ;  // a2
//   peak         250 Hz
crom[ 55] = 18'sd65780  ;  // b0
crom[ 56] = -18'sd129119;  // b1
crom[ 57] = 18'sd63409  ;  // b2
crom[ 58] = -18'sd129119;  // a1
crom[ 59] = 18'sd63652  ;  // a2
//   peak        1000 Hz
crom[ 60] = 18'sd64616  ;  // b0
crom[ 61] = -18'sd121084;  // b1
crom[ 62] = 18'sd57513  ;  // b2
crom[ 63] = -18'sd121084;  // a1
crom[ 64] = 18'sd56593  ;  // a2
//   peak        4000 Hz
crom[ 65] = 18'sd68628  ;  // b0
crom[ 66] = -18'sd92828 ;  // b1
crom[ 67] = 18'sd38561  ;  // b2
crom[ 68] = -18'sd92828 ;  // a1
crom[ 69] = 18'sd41653  ;  // a2
//   highshelf  12000 Hz
crom[ 70] = 18'sd82505  ;  // b0
crom[ 71] = -18'sd10263 ;  // b1
crom[ 72] = 18'sd7032   ;  // b2
crom[ 73] = 18'sd8152   ;  // a1
crom[ 74] = 18'sd5586   ;  // a2
// ---- POP (preset 3), preamp -0.88 dB
//   lowshelf      80 Hz
crom[ 75] = 18'sd65503  ;  // b0
crom[ 76] = -18'sd129881;  // b1
crom[ 77] = 18'sd64385  ;  // b2
crom[ 78] = -18'sd129881;  // a1
crom[ 79] = 18'sd64353  ;  // a2
//   peak         250 Hz
crom[ 80] = 18'sd65536  ;  // b0
crom[ 81] = -18'sd128893;  // b1
crom[ 82] = 18'sd63426  ;  // b2
crom[ 83] = -18'sd128893;  // a1
crom[ 84] = 18'sd63426  ;  // a2
//   peak        1000 Hz
crom[ 85] = 18'sd66469  ;  // b0
crom[ 86] = -18'sd122807;  // b1
crom[ 87] = 18'sd57398  ;  // b2
crom[ 88] = -18'sd122807;  // a1
crom[ 89] = 18'sd58331  ;  // a2
//   peak        4000 Hz
crom[ 90] = 18'sd70235  ;  // b0
crom[ 91] = -18'sd93784 ;  // b1
crom[ 92] = 18'sd38058  ;  // b2
crom[ 93] = -18'sd93784 ;  // a1
crom[ 94] = 18'sd42757  ;  // a2
//   highshelf  12000 Hz
crom[ 95] = 18'sd69419  ;  // b0
crom[ 96] = -18'sd2165  ;  // b1
crom[ 97] = 18'sd5831   ;  // b2
crom[ 98] = 18'sd2044   ;  // a1
crom[ 99] = 18'sd5505   ;  // a2
// ---- JAZZ (preset 4), preamp -0.90 dB
//   lowshelf      80 Hz
crom[100] = 18'sd65636  ;  // b0
crom[101] = -18'sd130007;  // b1
crom[102] = 18'sd64379  ;  // b2
crom[103] = -18'sd130008;  // a1
crom[104] = 18'sd64478  ;  // a2
//   peak         250 Hz
crom[105] = 18'sd65658  ;  // b0
crom[106] = -18'sd129009;  // b1
crom[107] = 18'sd63421  ;  // b2
crom[108] = -18'sd129009;  // a1
crom[109] = 18'sd63542  ;  // a2
//   peak        1000 Hz
crom[110] = 18'sd65536  ;  // b0
crom[111] = -18'sd121989;  // b1
crom[112] = 18'sd57506  ;  // b2
crom[113] = -18'sd121989;  // a1
crom[114] = 18'sd57506  ;  // a2
//   peak        4000 Hz
crom[115] = 18'sd64044  ;  // b0
crom[116] = -18'sd89746 ;  // b1
crom[117] = 18'sd39586  ;  // b2
crom[118] = -18'sd89746 ;  // a1
crom[119] = 18'sd38094  ;  // a2
//   highshelf  12000 Hz
crom[120] = 18'sd73533  ;  // b0
crom[121] = -18'sd4584  ;  // b1
crom[122] = 18'sd6195   ;  // b2
crom[123] = 18'sd4086   ;  // a1
crom[124] = 18'sd5521   ;  // a2
// ---- CLASSICAL (preset 5), preamp -0.55 dB
//   lowshelf      80 Hz
crom[125] = 18'sd65603  ;  // b0
crom[126] = -18'sd129978;  // b1
crom[127] = 18'sd64383  ;  // b2
crom[128] = -18'sd129979;  // a1
crom[129] = 18'sd64449  ;  // a2
//   peak         250 Hz
crom[130] = 18'sd65536  ;  // b0
crom[131] = -18'sd128893;  // b1
crom[132] = 18'sd63426  ;  // b2
crom[133] = -18'sd128893;  // a1
crom[134] = 18'sd63426  ;  // a2
//   peak        1000 Hz
crom[135] = 18'sd65536  ;  // b0
crom[136] = -18'sd121989;  // b1
crom[137] = 18'sd57506  ;  // b2
crom[138] = -18'sd121989;  // a1
crom[139] = 18'sd57506  ;  // a2
//   peak        4000 Hz
crom[140] = 18'sd62583  ;  // b0
crom[141] = -18'sd88646 ;  // b1
crom[142] = 18'sd39776  ;  // b2
crom[143] = -18'sd88646 ;  // a1
crom[144] = 18'sd36824  ;  // a2
//   highshelf  12000 Hz
crom[145] = 18'sd77890  ;  // b0
crom[146] = -18'sd7277  ;  // b1
crom[147] = 18'sd6594   ;  // b2
crom[148] = 18'sd6123   ;  // a1
crom[149] = 18'sd5548   ;  // a2
// ---- VOCAL (preset 6), preamp -0.45 dB
//   lowshelf      80 Hz
crom[150] = 18'sd65436  ;  // b0
crom[151] = -18'sd129809;  // b1
crom[152] = 18'sd64380  ;  // b2
crom[153] = -18'sd129808;  // a1
crom[154] = 18'sd64281  ;  // a2
//   peak         250 Hz
crom[155] = 18'sd65415  ;  // b0
crom[156] = -18'sd128770;  // b1
crom[157] = 18'sd63425  ;  // b2
crom[158] = -18'sd128770;  // a1
crom[159] = 18'sd63303  ;  // a2
//   peak        1000 Hz
crom[160] = 18'sd66943  ;  // b0
crom[161] = -18'sd123186;  // b1
crom[162] = 18'sd57306  ;  // b2
crom[163] = -18'sd123186;  // a1
crom[164] = 18'sd58713  ;  // a2
//   peak        4000 Hz
crom[165] = 18'sd68628  ;  // b0
crom[166] = -18'sd92828 ;  // b1
crom[167] = 18'sd38561  ;  // b2
crom[168] = -18'sd92828 ;  // a1
crom[169] = 18'sd41653  ;  // a2
//   highshelf  12000 Hz
crom[170] = 18'sd65536  ;  // b0
crom[171] = 18'sd0      ;  // b1
crom[172] = 18'sd5500   ;  // b2
crom[173] = 18'sd0      ;  // a1
crom[174] = 18'sd5500   ;  // a2
// ---- TREBLE (preset 7), preamp -1.17 dB
//   lowshelf      80 Hz
crom[175] = 18'sd65536  ;  // b0
crom[176] = -18'sd129915;  // b1
crom[177] = 18'sd64386  ;  // b2
crom[178] = -18'sd129915;  // a1
crom[179] = 18'sd64386  ;  // a2
//   peak         250 Hz
crom[180] = 18'sd65536  ;  // b0
crom[181] = -18'sd128893;  // b1
crom[182] = 18'sd63426  ;  // b2
crom[183] = -18'sd128893;  // a1
crom[184] = 18'sd63426  ;  // a2
//   peak        1000 Hz
crom[185] = 18'sd65536  ;  // b0
crom[186] = -18'sd121989;  // b1
crom[187] = 18'sd57506  ;  // b2
crom[188] = -18'sd121989;  // a1
crom[189] = 18'sd57506  ;  // a2
//   peak        4000 Hz
crom[190] = 18'sd68628  ;  // b0
crom[191] = -18'sd92828 ;  // b1
crom[192] = 18'sd38561  ;  // b2
crom[193] = -18'sd92828 ;  // a1
crom[194] = 18'sd41653  ;  // a2
//   highshelf  12000 Hz
crom[195] = 18'sd92572  ;  // b0
crom[196] = -18'sd17204 ;  // b1
crom[197] = 18'sd8039   ;  // b2
crom[198] = 18'sd12180  ;  // a1
crom[199] = 18'sd5691   ;  // a2

prom[0] = 18'sd65536  ;  // FLAT       -0.00 dB
prom[1] = 18'sd52832  ;  // BASS       -1.87 dB
prom[2] = 18'sd50662  ;  // ROCK       -2.24 dB
prom[3] = 18'sd59240  ;  // POP        -0.88 dB
prom[4] = 18'sd59056  ;  // JAZZ       -0.90 dB
prom[5] = 18'sd61548  ;  // CLASSICAL  -0.55 dB
prom[6] = 18'sd62243  ;  // VOCAL      -0.45 dB
prom[7] = 18'sd57301  ;  // TREBLE     -1.17 dB
